In [44]:
import pandas as pd

In [56]:
#데이터 프레임 생성 방법
data = {
    "name": ["동원","태규","희주","승재"],
    "age" : [32, 29, 28, 31],
    "score" : [3, 5, 4, 1]
}
df = pd.DataFrame(data)
df

  name  age  score
0   동원   32      3
1   태규   29      5
2   희주   28      4
3   승재   31      1

In [57]:
df.index = ['환자1', '환자2', '환자3', '환자4']
df

    name  age  score
환자1   동원   32      3
환자2   태규   29      5
환자3   희주   28      4
환자4   승재   31      1

In [58]:
# 단일 칼럼(Column) 선택
df['name']

환자1    동원
환자2    태규
환자3    희주
환자4    승재
Name: name, dtype: object

In [59]:
# 다중 칼럼(Column) 선택
df[['name','age']]

    name  age
환자1   동원   32
환자2   태규   29
환자3   희주   28
환자4   승재   31

In [49]:
# 행 선택 (loc) : 인덱스 이름 기반으로 선택
df.loc['환자1']

name     동원
age      32
score     3
Name: 환자1, dtype: object

In [60]:
df.loc[['환자1','환자2']] #다중 인덱스 선택

    name  age  score
환자1   동원   32      3
환자2   태규   29      5

In [61]:
# 행 선택 (iloc) : (정수 기반) 인덱스 행번호 선택
df.iloc[0]

name     동원
age      32
score     3
Name: 환자1, dtype: object

In [62]:
df.iloc[::2] #슬라이싱도 가능

    name  age  score
환자1   동원   32      3
환자3   희주   28      4

In [63]:
df.iloc[1::2][['name','age']] #슬라이싱 +컬럼만 추출

    name  age
환자2   태규   29
환자4   승재   31

In [64]:
df[df['age']>30] # 행 필터링

    name  age  score
환자1   동원   32      3
환자4   승재   31      1

In [65]:
df[(df["age"]>30) | (df["score"]>4)]  #여러 조건 결합

    name  age  score
환자1   동원   32      3
환자2   태규   29      5
환자4   승재   31      1

In [69]:
df.sort_values('age') # 오름차순

    name  age  score
환자3   희주   28      4
환자2   태규   29      5
환자4   승재   31      1
환자1   동원   32      3

In [70]:
df.sort_values('age',ascending=False) #내림차순

    name  age  score
환자1   동원   32      3
환자4   승재   31      1
환자2   태규   29      5
환자3   희주   28      4

In [71]:
# 값 수정하기
df.loc[df['name'] == '승재', 'score'] =6
df

    name  age  score
환자1   동원   32      3
환자2   태규   29      5
환자3   희주   28      4
환자4   승재   31      6

In [77]:
# 컬럼 추가
df["isYoung"] = df['age'] <30
df

    name  age  score  isYoung
환자1   동원   32      3    False
환자3   희주   28      4     True
환자4   승재   31      6    False

In [73]:
df

    name  age  score  isYoung
환자1   동원   32      3    False
환자2   태규   29      5     True
환자3   희주   28      4     True
환자4   승재   31      6    False

In [74]:
# Column(컬럼,열,세로)을 지우고 싶을때
df.drop(columns = ["isYoung"], inplace=True) 
# Columns = [""] 로 쓰거나 axis = 1
df

    name  age  score
환자1   동원   32      3
환자2   태규   29      5
환자3   희주   28      4
환자4   승재   31      6

In [75]:
# row(로우,행,가로) 지우고 싶을때
df.drop(index = ['환자2'], inplace=True) 

# index = [""] 로 쓰거나  Axis = 0 
df

    name  age  score
환자1   동원   32      3
환자3   희주   28      4
환자4   승재   31      6

In [78]:
# 위에 식이랑 같은 것
df = df.drop(columns = ["isYoung"])
df

    name  age  score
환자1   동원   32      3
환자3   희주   28      4
환자4   승재   31      6

In [80]:
# 행 추가
df.loc['환자2'] = ['태규',29,5]
df

    name  age  score
환자1   동원   32      3
환자3   희주   28      4
환자4   승재   31      6
환자2   태규   29      5

In [81]:
df.index = [1, 2, 3, 4]
df

  name  age  score
1   동원   32      3
2   희주   28      4
3   승재   31      6
4   태규   29      5

In [82]:
df.sort_index()

  name  age  score
1   동원   32      3
2   희주   28      4
3   승재   31      6
4   태규   29      5

In [90]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: pandas>=1.2 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from seaborn) (3.10.7)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/myenv/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [91]:
import seaborn as sns

In [92]:
df = sns.load_dataset('titanic')

In [93]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [95]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [4]:
import pandas as pd

In [6]:
import seaborn as sns

In [7]:
df = pd.read_csv('train.csv')
df

,ID,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,TRAIN_000,4,103,60,33,192,24.0,0.966,33,0
1,TRAIN_001,10,133,68,0,0,27.0,0.245,36,0
2,TRAIN_002,4,112,78,40,0,39.4,0.236,38,0
3,TRAIN_003,1,119,88,41,170,45.3,0.507,26,0
4,TRAIN_004,1,114,66,36,200,38.1,0.289,21,0
...,...,...,...,...,...,...,...,...,...,...
647,TRAIN_647,1,91,64,24,0,29.2,0.192,21,0
648,TRAIN_648,10,122,68,0,0,31.2,0.258,41,0
649,TRAIN_649,8,84,74,31,0,38.3,0.457,39,0
650,TRAIN_650,2,81,72,15,76,30.1,0.547,25,0
651,TRAIN_651,1,107,68,19,0,26.5,0.165,24,0