In [101]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression # 선형 회귀 분석 모델
from sklearn.metrics import mean_squared_error, r2_score # 수학공식 모아둔 패키지


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score,confusion_matrix, roc_curve, roc_auc_score
import pandas as pd
from sklearn.metrics import classification_report


from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline

In [17]:
iris = load_iris()

In [18]:
iris.target # 원래 나오는 값

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
X = iris.data
y = (iris.target == 0).astype(int)  # 0인 값은 1로 바꾸고 1,2는 모두 0 값으로 나오게함

In [20]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [22]:
model = LogisticRegression()

In [23]:
model.fit(X_train, y_train)

LogisticRegression()

In [24]:
y_test

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [25]:
y_pred = model.predict(X_test)
y_pred   # pred값과 test 값이 같음

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1])

In [46]:
y_proba = model.predict_proba(X_test) # y 값을 예측할 확률 (위에 각각의 0과 1로 예측할 확률=신뢰도) 각각 순서대로 99% 45% 41% 95% 예측확률을 가짐

In [31]:
confusion_matrix(y_test, y_pred)

array([[20,  0],
       [ 0, 10]])

In [33]:
accuracy_score(y_test, y_pred) # 정확도

1.0

In [35]:
precision_score(y_test, y_pred) # 정밀도

1.0

In [36]:
recall_score(y_test, y_pred) # 재현률

1.0

In [37]:
f1_score(y_test, y_pred)  # Precision과 Recall의 조화평균

1.0

In [47]:
y_proba[:,1]

array([4.55385779e-03, 9.58520512e-01, 5.40034424e-06, 6.13513643e-03,
       2.25748581e-03, 9.63198614e-01, 6.06507656e-02, 6.37960994e-04,
       3.03502235e-03, 2.72273531e-02, 1.08841436e-03, 9.74974390e-01,
       9.80864653e-01, 9.70317035e-01, 9.78952648e-01, 4.51726428e-03,
       1.61150629e-04, 2.72165121e-02, 7.65407072e-03, 2.19300520e-04,
       9.66047949e-01, 2.02072539e-03, 9.61368929e-01, 2.40334577e-04,
       5.73021354e-05, 5.09630724e-04, 1.36923149e-04, 1.23785768e-04,
       9.70092769e-01, 9.61459028e-01])

In [157]:
FPR, TPR, threshold = roc_curve(y_test, y_proba[:,1]) # 성능곡선

In [158]:
roc_auc_score(y_test, y_proba[:,1]) #곡선 아래 면적

0.8282828282828283

In [51]:
# Threshold함수 그냥 보고 넘어가세요

In [134]:
df = pd.read_csv('train.csv')

In [135]:
df_t = df.drop(['Outcome','Pregnancies'], axis=1).replace(0, None) 
# Outcome과 Pregnancies는 0이 결측치가 아니라 유의마한 값이기 때문에 빼고 나머지는 0에 none 넣어줌

In [136]:
df_t[['Outcome','Pregnancies']] = df[['Outcome','Pregnancies']]
# Outcome과 Pregnancies 값을 다시 넣어줌

In [137]:
df_t = df_t.dropna()
# 결측치 뻄

In [138]:
df_t

,ID,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Pregnancies
0,TRAIN_000,103,60,33,192,24.0,0.966,33,0,4
3,TRAIN_003,119,88,41,170,45.3,0.507,26,0,1
4,TRAIN_004,114,66,36,200,38.1,0.289,21,0,1
5,TRAIN_005,78,50,32,88,31.0,0.248,26,1,3
6,TRAIN_006,91,54,25,100,25.2,0.234,23,0,1
...,...,...,...,...,...,...,...,...,...,...
636,TRAIN_636,171,110,24,240,45.4,0.721,54,1,9
637,TRAIN_637,152,90,33,29,26.8,0.731,43,1,13
638,TRAIN_638,139,62,41,480,40.7,0.536,21,0,1
643,TRAIN_643,147,74,25,293,34.9,0.385,30,0,4
650,TRAIN_650,81,72,15,76,30.1,0.547,25,0,2

In [144]:
X = df_t.drop(['Outcome','ID'], axis=1)
X

,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Pregnancies
0,103,60,33,192,24.0,0.966,33,4
3,119,88,41,170,45.3,0.507,26,1
4,114,66,36,200,38.1,0.289,21,1
5,78,50,32,88,31.0,0.248,26,3
6,91,54,25,100,25.2,0.234,23,1
...,...,...,...,...,...,...,...,...
636,171,110,24,240,45.4,0.721,54,9
637,152,90,33,29,26.8,0.731,43,13
638,139,62,41,480,40.7,0.536,21,1
643,147,74,25,293,34.9,0.385,30,4
650,81,72,15,76,30.1,0.547,25,2

In [145]:
y = df_t['Outcome']
y

0      0
3      0
4      0
5      1
6      0
      ..
636    1
637    1
638    0
643    0
650    0
Name: Outcome, Length: 332, dtype: int64

In [146]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [147]:
model = LogisticRegression()

In [148]:
model.fit(X_train, y_train)

/opt/anaconda3/envs/myenv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [149]:
y_pred = model.predict(X_test)

In [150]:
y_proba = model.predict_proba(X_test)
y_proba

array([[0.80540161, 0.19459839],
       [0.90371382, 0.09628618],
       [0.83754421, 0.16245579],
       [0.96403869, 0.03596131],
       [0.91964711, 0.08035289],
       [0.86441398, 0.13558602],
       [0.25585659, 0.74414341],
       [0.37624406, 0.62375594],
       [0.67914981, 0.32085019],
       [0.24266155, 0.75733845],
       [0.21726339, 0.78273661],
       [0.54449928, 0.45550072],
       [0.90469726, 0.09530274],
       [0.96690933, 0.03309067],
       [0.74448421, 0.25551579],
       [0.90065319, 0.09934681],
       [0.9880306 , 0.0119694 ],
       [0.89873245, 0.10126755],
       [0.34137729, 0.65862271],
       [0.77788134, 0.22211866],
       [0.92404288, 0.07595712],
       [0.77392141, 0.22607859],
       [0.95679165, 0.04320835],
       [0.31754263, 0.68245737],
       [0.63952394, 0.36047606],
       [0.87818182, 0.12181818],
       [0.904179  , 0.095821  ],
       [0.95118347, 0.04881653],
       [0.57233116, 0.42766884],
       [0.9190917 , 0.0809083 ],
       [0.93368189, 0.06631811],
       [0.97018169, 0.02981831],
       [0.85718913, 0.14281087],
       [0.7566523 , 0.2433477 ],
       [0.88393261, 0.11606739],
       [0.83060157, 0.16939843],
       [0.90155133, 0.09844867],
       [0.71077115, 0.28922885],
       [0.9465894 , 0.0534106 ],
       [0.42646337, 0.57353663],
       [0.7410401 , 0.2589599 ],
       [0.76458109, 0.23541891],
       [0.80370634, 0.19629366],
       [0.83611969, 0.16388031],
       [0.69218077, 0.30781923],
       [0.28564922, 0.71435078],
       [0.98730249, 0.01269751],
       [0.09904352, 0.90095648],
       [0.80963753, 0.19036247],
       [0.87678183, 0.12321817],
       [0.97363241, 0.02636759],
       [0.89645516, 0.10354484],
       [0.89932752, 0.10067248],
       [0.85711203, 0.14288797],
       [0.65133982, 0.34866018],
       [0.77196735, 0.22803265],
       [0.80829462, 0.19170538],
       [0.862529  , 0.137471  ],
       [0.19794016, 0.80205984],
       [0.50905519, 0.49094481],
       [0.69401966, 0.30598034],
       [0.54712894, 0.45287106],
       [0.21943145, 0.78056855],
       [0.94497595, 0.05502405],
       [0.8575278 , 0.1424722 ],
       [0.93447199, 0.06552801],
       [0.19051265, 0.80948735]])

In [154]:
print(classification_report(y_test, y_pred, target_names=["Normal","Diabeties"]))

              precision    recall  f1-score   support

      Normal       0.76      0.93      0.84        45
   Diabeties       0.75      0.41      0.53        22

    accuracy                           0.76        67
   macro avg       0.76      0.67      0.68        67
weighted avg       0.76      0.76      0.74        67

In [155]:
roc_auc_score(y_test, y_proba[:,1])

0.8282828282828283

In [156]:
model.coef_

array([[ 3.87701769e-02, -1.17216286e-02, -1.51056454e-04,
        -1.87252894e-03,  9.17414154e-02,  5.18672512e-01,
         2.14759721e-02,  6.16431240e-02]])