# 데이터 다루기 (1): Pandas + Seaborn (Titanic)

## 진행 방법
1. 각 코드 셀의 `TODO` 부분을 채우세요.
2. 필요 시 마크다운 셀의 질문에 답을 적으세요.
3. 마지막에는 간단한 **셀프 체크** 코드가 제공됩니다.

---

## 0. 환경 준비
- 필요한 라이브러리를 임포트합니다.
- Seaborn의 `titanic` 데이터셋을 로드합니다. (만약 로드 실패 시, 대체용 축약 데이터프레임을 생성합니다.)

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# seaborn 내장 titanic 데이터셋 로드 (인터넷 연결/버전 이슈로 실패 시 사용 환경을 점검하세요)
titanic = sns.load_dataset("titanic")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

## 1. 데이터 개요 확인
### Q1-1. 상위 5행을 미리보기 하세요 (`head`)
### Q1-2. 전체 구조와 결측치 정보를 확인하세요 (`info`)
### Q1-3. 수치형 통계 요약을 확인하세요 (`describe`)

In [69]:
# Q1-1 TODO: titanic 데이터의 상위 5행을 확인하세요.
# 예: titanic.____()
print('=====데이터의 상위 5행=====')
titanic.head(5)
print(t)
# Q1-2 TODO: 데이터 구조 및 결측치 개요를 확인하세요.
# 예: titanic.____()
print('=====데이터 구조 =====')
titanic.info()

print('=====결측치 개요=====')
ti = titanic.isnull().sum()
print(i)

# Q1-3 TODO: 수치형 컬럼의 기초 통계를 요약하세요.
# 예: titanic.____()
print('=====수치형 컬럼의 기초 통계=====')
titanic.describe()

=====데이터의 상위 5행=====
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True
=====데이터 구조 =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 1 to 891
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
=====결측치 개요=====
survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
=====수치형 컬럼의 기초 통계=====

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

## 2. 컬럼 / 인덱스 / 선택
### Q2-1. 컬럼 이름을 확인하세요 (`columns`)
### Q2-2. `sex`, `age`, `fare` 컬럼만 선택해 상위 3행을 보세요
### Q2-3. `iloc`으로 0~4행, 0~2열을 선택하세요
### Q2-4. `loc`으로 인덱스 1~5 범위에서 `sex`, `age`만 선택하세요 (인덱스는 1부터 시작하도록 재설정)

In [85]:
# Q2-1 TODO: 컬럼 이름 보기
list(titanic.columns)

['survived',
 'pclass',
 'sex',
 'age',
 'sibsp',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [45]:
# Q2-2 TODO: 특정 컬럼만 선택하여 상위 3행 보기
titanic.iloc[:3][['sex','age','fare']]

      sex   age     fare
1    male  22.0   7.2500
2  female  38.0  71.2833
3  female  26.0   7.9250

In [35]:
# 인덱스를 1부터 시작하도록 재설정
titanic.index = range(1, len(titanic) + 1)

# Q2-3 TODO: iloc으로 0~4행, 0~2열 선택
titanic.iloc[:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [36]:
# Q2-4 TODO: loc으로 인덱스 1~5 범위에서 sex, age 선택
titanic.loc[:5][['sex','age']]

      sex   age
1    male  22.0
2  female  38.0
3  female  26.0
4  female  35.0
5    male  35.0

## 3. 필터링 & 정렬
### Q3-1. 나이가 60 이상인 승객만 필터링하세요
### Q3-2. 여성(`sex == 'female'`) 이고 1등석(`pclass == 1`)인 승객만 필터링하세요
### Q3-3. 요금(`fare`)이 높은 순으로 5명만 보이세요 (`sort_values`)

In [50]:
# Q3-1 TODO : 나이가 60 이상인 승객만 필터링하세요
titanic[titanic['age'] >= 60 ]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
34,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
55,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False
97,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
117,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
171,0,1,male,61.0,0,0,33.5000,S,First,man,True,B,Southampton,no,True
253,0,1,male,62.0,0,0,26.5500,S,First,man,True,C,Southampton,no,True
276,1,1,female,63.0,1,0,77.9583,S,First,woman,False,D,Southampton,yes,False
281,0,3,male,65.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
327,0,3,male,61.0,0,0,6.2375,S,Third,man,True,NaN,Southampton,no,True
367,1,1,female,60.0,1,0,75.2500,C,First,woman,False,D,Cherbourg,yes,False
439,0,1,male,64.0,1,4,263.0000,S,First,man,True,C,Southampton,no,False
457,0,1,male,65.0,0,0,26.5500,S,First,man,True,E,Southampton,no,True
484,1,3,female,63.0,0,0,9.5875,S,Third,woman,False,NaN,Southampton,yes,True
494,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
546,0,1,male,64.0,0,0,26.0000,S,First,man,True,NaN,Southampton,no,True
556,0,1,male,62.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
571,1,2,male,62.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,yes,True
588,1,1,male,60.0,1,1,79.2000,C,First,man,True,B,Cherbourg,yes,False
626,0,1,male,61.0,0,0,32.3208,S,First,man,True,D,Southampton,no,True
631,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
673,0,2,male,70.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
685,0,2,male,60.0,1,1,39.0000,S,Second,man,True,NaN,Southampton,no,False
695,0,1,male,60.0,0,0,26.5500,S,First,man,True,NaN,Southampton,no,True
746,0,1,male,70.0,1,1,71.0000,S,First,man,True,B,Southampton,no,False
830,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True
852,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [51]:
# 여성(sex == 'female') 이고 1등석(pclass == 1)인 승객만 필터링하세요
titanic[(titanic['sex'] == 'female') & (titanic['pclass'] == 1)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
4,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
12,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
32,1,1,female,NaN,1,0,146.5208,C,First,woman,False,B,Cherbourg,yes,False
53,1,1,female,49.0,1,0,76.7292,C,First,woman,False,D,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,1,1,female,45.0,1,1,164.8667,S,First,woman,False,NaN,Southampton,yes,False
863,1,1,female,48.0,0,0,25.9292,S,First,woman,False,D,Southampton,yes,True
872,1,1,female,47.0,1,1,52.5542,S,First,woman,False,D,Southampton,yes,False
880,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
888,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [58]:
# Q3-3 TODO : 요금(fare)이 높은 순으로 5명만 보이세요 (sort_values)
five = titanic.sort_values('fare', ascending=False)
five[:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
259,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
738,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
680,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
89,1,1,female,23.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False
28,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False

## 4. 결측치 처리
### Q4-1. `age` 결측치를 평균으로 채우세요 (`fillna`) - 원본 수정
### Q4-2. `embarked` 결측치를 최빈값으로 채우세요 (`mode()[0]`) - 원본 수정
### Q4-3. `age`가 결측인 행을 제거하세요 (`dropna(subset=[...])`) 대신, 여기서는 이미 Q4-1에서 채웠다면 예시로 `fare`의 결측이 있다면 제거해보세요

In [61]:
# Q4-1 TODO: age 평균으로 채우기
titanic['age'].fillna(titanic['age'].mean(),inplace=True)
titanic

/var/folders/7d/4294lrxx67jdcn0_3qst6jf00000gn/T/ipykernel_39311/552112149.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['age'].fillna(titanic['age'].mean(),inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
891,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [62]:
# Q4-2 TODO: embarked 최빈값으로 채우기
titanic['embarked'].fillna(titanic['embarked'].mode(),inplace=True)
titanic

/var/folders/7d/4294lrxx67jdcn0_3qst6jf00000gn/T/ipykernel_39311/3436351019.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['embarked'].fillna(titanic['embarked'].mode(),inplace=True)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
891,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [71]:
# Q4-3 TODO: 특정 컬럼 결측치 행 제거
titanic['age'].dropna()

1      22.000000
2      38.000000
3      26.000000
4      35.000000
5      35.000000
         ...
887    27.000000
888    19.000000
889    29.699118
890    26.000000
891    32.000000
Name: age, Length: 891, dtype: float64

## 5. 파생변수 & 값 수정
### Q5-1. 나이가 18세 이상이면 `is_adult=True`, 아니면 False인 컬럼을 추가하세요
### Q5-2. `fare`가 0인 경우를 평균 요금으로 대체하세요 (`loc` 활용)
### Q5-3. 방금 만든 `is_adult` 컬럼을 삭제해보세요 (`drop`)

In [73]:
# Q5-1 TODO: is_adult 파생변수 추가
titanic['is_adult'] = titanic['age'] >= 18
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,is_adult
1,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
2,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True
3,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
4,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
5,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
888,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
889,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
890,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
891,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [76]:
# Q5-2 TODO: 요금이 0인 경우 평균 요금으로 대체
titanic['fare'].fillna(titanic['fare'].mean,inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,is_adult
1,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,True
2,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,True
3,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,True
4,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,True
5,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True,True
888,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True,True
889,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False,True
890,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True,True
891,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,True

In [77]:
# Q5-3 TODO: is_adult 컬럼 삭제
titanic.drop(columns = ["is_adult"], inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,0,3,male,22.000000,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,1,female,38.000000,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
3,1,3,female,26.000000,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,1,1,female,35.000000,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
5,0,3,male,35.000000,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,male,27.000000,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,1,1,female,19.000000,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,0,3,female,29.699118,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,1,1,male,26.000000,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
891,0,3,male,32.000000,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## 6. 저장 & 불러오기 (옵션)
### Q6-1. 현재 DataFrame을 `titanic_clean.csv`로 저장하세요 (`to_csv`, `index=False`)
### Q6-2. 방금 저장한 파일을 다시 불러오세요 (`read_csv`)

In [83]:
# Q8-1 TODO: 저장
titanic.to_csv('titanic_clean.csv',index=False)

In [84]:
# Q8-2 TODO: 재로딩
titanic = pd.read_csv('titanic_clean.csv')